name: Godot Export
on:
  push:
    branches:
      - develop
      - test
env:
  GODOT_VERSION: 4.3
  GODOT_RELEASE: stable

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and setup Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-${GODOT_RELEASE}/Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_linux.x86_64.zip
          unzip Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_linux.x86_64.zip
          mv Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_linux.x86_64 godot
          chmod +x godot
          
      - name: Setup export templates
        run: |
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-${GODOT_RELEASE}/Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.${GODOT_RELEASE}
          unzip Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_export_templates.tpz
          mv templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.${GODOT_RELEASE}/
          rm -rf templates
          
      - name: Clear export folder
        run: |
          rm -rf Export
          mkdir -p Export

      - name: Export project
        run: |
          ./godot --headless --export-release "Web" "Export/index.html"
          fi
          EXIT_CODE=$?
          echo "Godot export exit code: $EXIT_CODE"
          echo "Contents of Export directory:"
          ls -la Export
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Export failed. Godot log:"
            cat ~/.config/godot/editor_log.txt
            exit 1
          fi

      - name: Clean and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            APP_DIR=${{ secrets.APP_DIR }}
            rm -rf $APP_DIR/*
            mkdir -p $APP_DIR

      - name: Upload files to server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete
          path: Export/
          remote_path: ${{ secrets.APP_DIR }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
